# Generated by Django 3.2.5 on 2022-06-24 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_rename_events_likeevent_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeevent',
            unique_together={('event', 'user')},
        ),
    ]
